services:
  frontend:
    build: ./frontend
    networks:
      - frontendNet
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - database
  backend:
    build: ./backend
    networks:
      - backendNet
      - frontendNet
    ports:
      - "3000:3000"
    secrets:
      - password_database
    depends_on:
      - database
  database:
    image: mongo:latest
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backendNet
    secrets:
      - password_database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/password_database
      - MONGO_INITDB_DATABASE=blog

networks:
  backendNet:
  frontendNet:

volumes:
  db_data:

secrets:
  password_database:
    file: ./databasePassword.env